name: Build

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]
  release:
    type: [created, edited]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest

    runs-on: ${{matrix.os}}

    steps:
    - uses: actions/checkout@v2

    - name: "Windows: Configure environment"
      if: runner.os == 'Windows'
      shell: bash
      run: |
        # Select MinGW toolchain instead of the default MSVC.
        echo "CMAKE_GENERATOR=MinGW Makefiles" >> $GITHUB_ENV

    - name: Configure CMake
      working-directory: ${{github.workspace}}
      run: cmake -B ${{github.workspace}}/build

    - name: Build
      working-directory: ${{github.workspace}}
      run: cmake --build ${{github.workspace}}/build

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}}
      
    - uses: actions/upload-artifact@v2
      with:
        name: binaries
        path: ${{github.workspace}}/build/*.xpl
        if-no-files-found: error