name: Build

on:
  push:
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: lin
          - os: windows-latest
            target: win
          - os: macos-latest
            target: mac

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Build
        run: make OS=${{ matrix.target }}

      - name: Upload
        uses: actions/upload-artifact@v7
        with:
          name: ${{ matrix.target }}
          path: build/${{ matrix.target }}/*.xpl
