name: Build

on:
  push:
    branches: [native]
  pull_request:
    branches: [native]
  release:
    type: [created, edited]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest

    runs-on: ${{matrix.os}}

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: "Windows: Configure environment"
      if: runner.os == 'Windows'
      shell: bash
      run: |
        choco install git cmake

    - name: "Linux: Install dependency libraries"
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends cmake

    - name: Build
      working-directory: ${{github.workspace}}
      run: |
        mkdir build
        cd build
        cmake ..
        make Makefile
      
    - uses: actions/upload-artifact@v2
      with:
        name: binaries
        path: ${{github.workspace}}/build/*.xpl
        if-no-files-found: error
