name: Build

on:
  push:
    branches: [native]
  pull_request:
    branches: [native]
  release:
    type: [created, edited]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest

    runs-on: ${{matrix.os}}

    steps:
    - uses: actions/checkout@v2
    - uses: ilammy/msvc-dev-cmd@v1

    - name: Build for windows
      if: runner.os == 'Windows'
      working-directory: ${{github.workspace}}
      run: |
        mkdir build
        cd build
        cmake .. -G "NMake Makefiles"
        nmake

    - name: Build for linux or macos
      if: runner.os != 'Windows'
      working-directory: ${{github.workspace}}
      run: |
        mkdir build
        cd build
        cmake ..
        make
      
    - uses: actions/upload-artifact@v2
      if: runner.os == 'Windows'
      with:
        name: win
        path: ${{github.workspace}}/build/*.xpl
        if-no-files-found: error

    - uses: actions/upload-artifact@v2
      if: runner.os == 'Linux'
      with:
        name: lin
        path: ${{github.workspace}}/build/*.xpl
        if-no-files-found: error

    - uses: actions/upload-artifact@v2
      if: runner.os == 'macOS'
      with:
        name: mac
        path: ${{github.workspace}}/build/*.xpl
        if-no-files-found: error